### ISSUE TITLE
Textures missing in RedwoodForest

### ISSUE THREAD

**Issue by joshgreaves** [BYU-PCCL/holodeck#11]
Some trees are missing textures in the Linux build of the RedwoodForest.

**Comment by MaxRobinsonTheGreat** [comment]
If run with opengl3 it should work. Needs to be tested more, but if this consistently fixes the problem I don't think it requires any additional code.

**Comment by MaxRobinsonTheGreat** [comment]
Maybe in the long run the config should denote an opengl version for each map and then users wouldn't have to worry about it.

**Comment by MaxRobinsonTheGreat** [comment]
No longer an issue in ue4.21
