### ISSUE TITLE
Rendering options

### ISSUE THREAD

**Issue by kolbytn** [BYU-PCCL/holodeck#136]
Add rendering options on start up including no render. Test and document how to disable rendering during execution.

**Comment by jaydenmilne** [comment]
The "disabling rendering" was done as part of #135, I added a command that can be sent. (see #146 and BYU-PCCL/holodeck-engine#119)

For adjusting rendering options, we could either (1) do what I did above and abuse console commands (easy) or (2) do it the Right™ way and poke at the renderer's data structures (harder) or (3) do more research to figure out how you're "supposed" to do this in UE4
