### ISSUE TITLE
Tasks -> C++, Task Configuration

### ISSUE THREAD

**Issue by nickwalton** [BYU-PCCL/holodeck#142]
Task's are pretty opaque for users currently. They should be moved to C++ code so that it is clear to users how task rewards are calculated. It would also be nice to have some way that a user could configure task set up.

**Comment by jaydenmilne** [comment]
As part of this we should migrate tasks to be configured entirely client side (location, MainAgent, etc)

**Comment by jaydenmilne** [comment]
Fixed in BYU-PCCL/holodeck-engine#151
