### ISSUE TITLE
`HolodeckEnvironment` class is huge

### ISSUE THREAD

**Issue by jaydenmilne** [BYU-PCCL/holodeck#196]
1. Trim down constructor arguments
2. Move debug drawing functions somewhere else
    - Subclass? ie `env.debug.drawline()`
    - takes environment as variable? ie `drawDebugLine(env)`
3. Move weather/time functions somewhere else

Should the environment be an object acted upon more?

**Comment by jaydenmilne** [comment]
There are a lot of commands that are simple wrappers for `Command` objects - maybe instead of providing these helper functions, we can just educate the user into sending their own commands.

**Comment by jaydenmilne** [comment]
See #207

**Comment by jaydenmilne** [comment]
I've trimmed down the constructor arguments. I've also removed a lot of the agent manipulation stuff (teleport, set physics state, etc) to the Agent class as well, we just need to move the debug stuff and the weather stuff.

**Comment by jaydenmilne** [comment]
When  #263 is done this can be closed probably

**Comment by vinhowe** [comment]
@jaydenmilne Can this be closed now that #372 is in?
