### ISSUE TITLE
Spawn agent collision causes crash

### ISSUE THREAD

**Issue by MaxRobinsonTheGreat** [BYU-PCCL/holodeck#210]
If you attempt to spawn two agents in the same place the game will crash. We should be able to handle this and print some sort of error message to the screen or at least to the log.

**Comment by MaxRobinsonTheGreat** [comment]
May have been fixed, but needs to be tested.

**Comment by jaydenmilne** [comment]
Tested this, doesn't crash it, but it does cause interesting results

![Peek 2019-05-08 16-53](https://user-images.githubusercontent.com/7662768/58042156-26eba900-7af7-11e9-939c-1300bc8b6650.gif)
