### ISSUE TITLE
More thorough testing of Android joint and pressure sensors.

### ISSUE THREAD

**Issue by MaxRobinsonTheGreat** [BYU-PCCL/holodeck#211]
It seems like the joint and pressure sensors are working correctly, but they are difficult to test and need more thorough testing. Issue originally posted by @nickwalton BYU-PCCL/holodeck-engine#92

**Comment by jaydenmilne** [comment]
Added some tests in #298.

I'm reasonably confident that the joint rotation sensors are working. I fixed the order of the RelativeSkeletalPositionSensor since it was wrong before; now I'm fairly sure that they are working.
