### ISSUE TITLE
Infinite forest crash on Windows

### ISSUE THREAD

**Issue by MaxRobinsonTheGreat** [BYU-PCCL/holodeck#228]
**Description**
The infinite forest world crashes on windows after loading up a different environment first

**To Reproduce**
Go to defaultworlds_pytest.py and move `test_infiniteforest` so that it is not the first test. Run `pytest holodeck/tests/defaultworlds_pytest.py` and it will crash when loading up the infinite forest

**Comment by jaydenmilne** [comment]
Fixed in BYU-PCCL/holodeck-engine#175
