### ISSUE TITLE
Agent follower should follow main agent

### ISSUE THREAD

**Issue by MaxRobinsonTheGreat** [BYU-PCCL/holodeck#238]
When the world is spawned, maybe a command should be sent to connect the agent follower with the tag "mainagent"

**Comment by jaydenmilne** [comment]
This will fix the "nav agent's foot" bug

**Comment by MaxRobinsonTheGreat** [comment]
> This will fix the "nav agent's foot" bug

It actually won't fix that bug, but the agent follower will no longer default to showing the nav agent in the cyberpunkcity world, which looks bad.

#319

**Comment by MaxRobinsonTheGreat** [comment]
#320
