### ISSUE TITLE
Bump engine version to 4.22

### ISSUE THREAD

**Issue by jaydenmilne** [BYU-PCCL/holodeck#241]
**Describe the new feature you'd like**
Apparently 4.22 improves the cook time for projects, and renders static meshes faster

- [ ] Update .uproject
- [ ] Generate new UE4-docker docker image on monster
- [ ] Come up with transition strategy
- [ ] Remove all warnings from the upgrade

**Comment by MaxRobinsonTheGreat** [comment]
Finished BYU-PCCL/holodeck-engine#182

**Comment by jaydenmilne** [comment]
✔ in changelog
