### ISSUE TITLE
Significant discrepancy between Viewport and RGBCamera

### ISSUE THREAD

**Issue by MaxRobinsonTheGreat** [BYU-PCCL/holodeck#252]
**Describe**
There can be major differences between the viewport and rgbcamera, which can cause a misunderstanding in what the user thinks the agent is seeing. This is most apparent in the InfiniteForest world, where the lighting is almost pitch black in the camera sensor but looks normal from the viewport, well after the pre-start steps. 

**To Reproduce**
Run the infiniteforest world and display the rgbcamera sensor's captured pixels. Most are black, and only a few are slightly lighter than that. It is not a broken sensor - an image of the world is being captured but is extremely dark.

**Screenshots**
RGBCamera capture after 200 ticks:
![capture](https://user-images.githubusercontent.com/9001247/57959948-734ea300-78c3-11e9-9b8b-1f063701b5c9.png)

Similar capture from the viewport:
![Capture](https://user-images.githubusercontent.com/9001247/57960216-d5f46e80-78c4-11e9-9931-d9153bd74454.PNG)

**Version Information:**
 - OS: Linux and Windows
 - Version 0.2.1
 - InfiniteForest-MaxDistance

We may fix this by making the infinite forest world brighter, but this would cause the world to look washed out in the viewport and fails to fix the root of the problem.

**Comment by jaydenmilne** [comment]
Are we sure this isn't present in 0.1.0?

**Comment by jaydenmilne** [comment]
This looks helpful: http://www.cs.jhu.edu/~qiuwch/unrealcv/plugin/3de2bd7/Source/UnrealCV/Private/GTCaptureComponent.cpp

**Comment by jaydenmilne** [comment]
Reproduced on v0.1.0
![render1](https://user-images.githubusercontent.com/7662768/58038313-e9821e00-7aec-11e9-9461-6581218a5046.png)
![render2](https://user-images.githubusercontent.com/7662768/58038316-eb4be180-7aec-11e9-8534-8eb72bdb6e3b.png)

**Comment by jaydenmilne** [comment]
This looks like an HDR thing to me

**Comment by jaydenmilne** [comment]
Or it could be because of the small resolution of the camera

**Comment by MaxRobinsonTheGreat** [comment]
Increased lighting in infinite forest did not fix the issue. This did: BYU-PCCL/holodeck-engine#180
