### ISSUE TITLE
CupWorld and CupTask

### ISSUE THREAD

**Issue by jaydenmilne** [BYU-PCCL/holodeck#288]
The goal is to create a moving cup game to focus on "object persistence and tracking; hidden state estimation"

### CupWorld
A small room with a table, three cups, a chair, and a window facing east/west so the sun can cast shadows, etc.

### CupTask

The CupTask should roughly follow this sequence:

1. After the level starts, wait a second or so
2. Pick a cup that has the "prize" in it. Lift it up and show it to the agent
3. De-spawn the prize once the cup is back down
4. Randomly shuffle the cups. We should allow the number of exchanges to be configured
5. Stop moving the cups. Somehow signal the agent that it should pick
6. Let the agent pick which cup it wants.
    It would be good to have these options available to adjust difficulty:
    - Giving a number 1-3 to identify the cup
    - Touching the cup
    - Lifting the cup up 
7. Give reward if correct
8. Terminal

Immediately give terminal if the agent prematurely chooses a cup

#### Implementation Ideas

The code for the task should be in C++ in holodeck-engine, but the assets will probably need to be in `holodeck-worlds`

The task needs to have
- A reference to the cups to move them. Tags should be fine (eg `cup1`, `cup2`, etc)
- The cups need to be able to inform the task when they are touched or moved
  - Emit an event? https://wiki.unrealengine.com/Simple_Global_Event_System

The task can probably spawn/despawn the prize as well, it will probably just be a little colored sphere.

**Comment by MaxRobinsonTheGreat** [comment]
#318
