### ISSUE TITLE
CupGame Scenarios

### ISSUE THREAD

**Issue by jaydenmilne** [BYU-PCCL/holodeck#289]
Create some scenarios that use the CupTask and CupWorld (#288) 
(goal: object persistence and tracking; hidden state estimation)

#### Ideas:
- `BasicCupGame`
  - Only swap the cups 2 or 3 times
  - Use the "pick a cup" control scheme, don't require it to touch
- `TouchCupGameHand`
  - Swap the cups a good 10 times or so
  - `FloatingHandAgent`
  - Require agent to just touch the cup
- `TouchCupGameAndroid`
  - Same as `CupGameHand`, but using the full Android agent
- `CupGameHand`
  - Similar to `TouchCupGameHand`, but the agent must lift the cup
- `CupGameAndroid`
  - Similar to `CupGameHand`, but with the android

**Comment by MaxRobinsonTheGreat** [comment]
The suggested scenarios were changed up a bit, see BYU-PCCL/holodeck-configs/pull/12 for details
