### ISSUE TITLE
TrashWorld and TrashTask

### ISSUE THREAD

**Issue by jaydenmilne** [BYU-PCCL/holodeck#290]
Create a world and a task for picking up trash to focus on 
**Goal**: support/attachment/containment; planning

### GarbageWorld
Medium sized room with a table that has a trash can next to it, and lots of room on the floor. Windows

### GarbageTask
Task that gives reward for moving trash objects to trashcan.

TODO: Should we have a variety of things that are realistic? IE soda cups, etc

- On level start, the TrashTask should spawn a configurable amount of trash defined in a "trash region" - a rectangular volume.
- Reward is given for having the trash collide with the "trash can" - another rectangular volume, presumably placed at the top of a trash can. 
  - Despawn the trash when it touches this. 
- Go terminal when all of the trash is in the can

**Comment by MaxRobinsonTheGreat** [comment]
Renamed to clean up world so Max doesn't have to say he built a trash world #321
