### ISSUE TITLE
TrashScenarios

### ISSUE THREAD

**Issue by jaydenmilne** [BYU-PCCL/holodeck#291]
Create scenarios to use with TrashTask (#290)

#### Ideas
- `KnockIntoTrashCan` - One piece of trash is on table next to trash can, agent just has to bump it off basically
- `CarryIntoTrashCan` - One piece of trash is a moderate distance away from the can
- `CleanupTrash` - Trash is scattered in the room, agent must place it all in the "trash can" 

#### Other Worlds
We might be able to use other worlds with the `TrashTask` if we just add a "can" to them
- `MazeWorld` 
- `AndroidPlayground`

**Comment by MaxRobinsonTheGreat** [comment]
BYU-PCCL/holodeck-configs/pull/12
