### ISSUE TITLE
Optionally add a slight bit of randomization to agent start location

### ISSUE THREAD

**Issue by jaydenmilne** [BYU-PCCL/holodeck#295]
David mentioned that it might be good to have the start location of agents randomized a bit (less than half a meter or so in each direction) on reset to add a bit of entropy.

It would be good if this were configurable per-scenario in the config file, ie "start location randomization"

**Comment by jaydenmilne** [comment]
Adjusting the rotation a bit would be good as well

**Comment by jaydenmilne** [comment]
<this was David's idea>

**Comment by daniekpo** [comment]
Fixed in commit dc2f22e.

**Comment by jaydenmilne** [comment]
✅ in changelog
