### ISSUE TITLE
UAV agent's motors all spin same direction

### ISSUE THREAD

**Issue by sethmnielsen** [BYU-PCCL/holodeck#331]
**Describe the bug**
The UAV's propellers are all animated to spin clockwise. 

**To Reproduce**
Please provide sample code to reproduce the bug.

**Expected behavior**
It should be clockwise front-left and back-right, counter-clockwise for front-right and back-left motors.

**Screenshots**
It should look like this:

![Screenshot from 2019-09-27 17-00-56](https://user-images.githubusercontent.com/13698678/65806768-73e82780-e148-11e9-8ea7-3c241361e39d.png)

I know this doesn't affect anything, I'm just bringing this up for purposes of aesthetics. :)

**Comment by jaydenmilne** [comment]
https://www.youtube.com/watch?v=hou0lU8WMgo

**Comment by MaxRobinsonTheGreat** [comment]
BYU-PCCL/holodeck-engine#199

**Comment by jaydenmilne** [comment]
white_check_mark in changelog
