### ISSUE TITLE
Can't install on linux

### ISSUE THREAD

**Issue by insooneelife** [BYU-PCCL/holodeck#346]
**Describe the bug**

Error install on linux.

![image](https://user-images.githubusercontent.com/8437769/68930319-73c3ea00-07d1-11ea-9910-b33a5bd1fa2e.png)

**To Reproduce**
Please provide sample code to reproduce the bug.

Follow up the instructions for linux installation.
https://holodeck.readthedocs.io/en/latest/usage/installation.html

**Expected behavior**

**Screenshots**

**Version Information:**
Linux Ubuntu 16.04

 - Holodeck Version
 - World/Scenario version

**Additional context**

**Comment by jaydenmilne** [comment]
You need to use python3, eg `pip3 install holodeck`


Try installing the dev headers for `python3` too:


`pip3 install python3-dev`

**Comment by jaydenmilne** [comment]
Did this resolve your issue?

**Comment by daniekpo** [comment]
@insooneelife, were you able to follow the instructions to resolve this issue? Can we close the issue?

**Comment by jaydenmilne** [comment]
Assuming this was because the package was not installed.
