### ISSUE TITLE
Improve Docker Experience

### ISSUE THREAD

**Issue by jaydenmilne** [BYU-PCCL/holodeck#347]
**Describe the new feature you'd like**
We've got some feedback for the Docker images we provide for Holodeck

- [x] Include OpenCV and other useful depends
- [x] Clone holodeck source code in image
- [x] Make sure tests run (`tox` / `pytest`) in docker container
- [x] Integrate testing docker images into the release checklist
- [x] Automate docker builds and testing in Jenkins?

**Comment by vinhowe** [comment]
Did we determine we were ready to close this?

**Comment by jaydenmilne** [comment]
✅ in changelog
