### ISSUE TITLE
Outdated Docs - Getting Started

### ISSUE THREAD

**Issue by joshgreaves** [BYU-PCCL/holodeck#352]
**Describe the bug**
The quick start guide described here https://holodeck.readthedocs.io/en/latest/usage/getting-started.html#getting-started uses the following code snippet:
`from holodeck.sensors import Sensors`
However, trying this import fails. It looks like there is no Sensors object in sensors.py

**To Reproduce**
I'm running on colab:
```
!pip install holodeck
from holodeck.sensors import Sensors
```

**Expected behavior**
The docs should clearly represent the correct way of getting the correct sensor.

**Screenshots**
N/A

**Version Information:**
 - OS: 
 - Version
 - Holodeck Version 0.3
 - World/Scenario version

**Additional context**
N/A

**Comment by MaxRobinsonTheGreat** [comment]
This looks fixed. I'm going to go ahead and close this.
