### ISSUE TITLE
DistanceTask: Agents can fly straight up for infinite reward

### ISSUE THREAD

**Issue by jaydenmilne** [BYU-PCCL/holodeck#360]
**Describe the bug**
We need to make the DistanceTask not consider the y axis as distance, since then the optimal strategy would then be to fly straight up.

**Expected behavior**
The default behavior should be to only consider the xy distance. We should add a flag on the DistanceTask config block that allows a user to opt-in to computing the full xyz distance if they want.

**Comment by MaxRobinsonTheGreat** [comment]
#363

**Comment by jaydenmilne** [comment]
✅ in changelog
