### ISSUE TITLE
Editor crashes when an agent is manually added

### ISSUE THREAD

**Issue by MaxRobinsonTheGreat** [BYU-PCCL/holodeck#361]
**Describe the bug**
The engine crashes when an agent is manually placed in a world rather than dynamically spawned. Though this is no longer a common use case, it should be fixed to avoid future confusion and potential use cases.

**To Reproduce**
Drag and drop a uav into the example level. Start the game and it will crash.

**Expected behavior**
The engine should not crash.

**Version Information:**
 - OS: Linux and Windows
 - Holodeck version: 0.3.0

**Additional context**
This is likely caused by the agent not being properly initialized. We should make sure all the initialization functions are being called.

**Comment by MaxRobinsonTheGreat** [comment]
#366

**Comment by jaydenmilne** [comment]
✅ in changelog
