### ISSUE TITLE
Document Torque Limits for Agents

### ISSUE THREAD

**Issue by jaydenmilne** [BYU-PCCL/holodeck#369]
**Describe the new feature you'd like**
For every control scheme 

- [x] Document Android control schemes (see [HandAgent](https://holodeck.readthedocs.io/en/latest/agents/hand-agent.html#control-schemes))
- [x] Document UAV control scheme maximum values
- [x] Look into adding scaled thrust control scheme for UAV
- [x] Look at other agents

If you have questions ask @kolbytn

**Comment by kolbytn** [comment]
It would be great if these limits were available in the `ContinuousActionSpace`. Additionally, the `_low` and `_high` properties of the `DiscreteActionSpace` class should be made accessible.

**Comment by daniekpo** [comment]
Resolved. See PR #380

**Comment by jaydenmilne** [comment]
✅ in changelog
