### ISSUE TITLE
Add sunny weather to available weather types

### ISSUE THREAD

**Issue by MaxRobinsonTheGreat** [BYU-PCCL/holodeck#376]
**Describe the new feature you'd like**
You can set the weather to sunny. Previously I assumed that all worlds would be sunny by default but as of #375 this will no longer be the case, making it useful to allow for the weather to be set to sunny.

**Comment by jaydenmilne** [comment]
https://youtu.be/MrHxhQPOO2c?t=17

**Comment by vinhowe** [comment]
@MaxRobinsonTheGreat are we ready to close this?

**Comment by jaydenmilne** [comment]
✅ in changelog
