### ISSUE TITLE
MazeWorld tests skips when DefaultWorlds is correctly installed

### ISSUE THREAD

**Issue by vinhowe** [BYU-PCCL/holodeck#381]
**Describe the bug**
A check in the MazeWorld tests prevents them from running when DefaultWorlds is installed. This check is incorrectly negated:

https://github.com/BYU-PCCL/holodeck/blob/0b16b496a441d2a31008d828fe9ec4ef32c23909/tests/worlds/mazeworld/conftest.py#L26-L28

**To Reproduce**
Run pytest on `worlds` directory.

**Expected behavior**
These tests should run if DefaultWorlds is installed.

**Comment by jaydenmilne** [comment]
¯\_(ツ)_/¯

**Comment by jaydenmilne** [comment]
When you see something minor like this you can just PR it directly, no need
to open an issue, especially since it was introduced so recently

**Comment by jaydenmilne** [comment]
Doesn't need to be in changelog
