### ISSUE TITLE
CleanUp docs page is broken

### ISSUE THREAD

**Issue by jaydenmilne** [BYU-PCCL/holodeck#385]
https://holodeck.readthedocs.io/en/latest/packages/Dexterity/CleanUp/clean-up.html
Images aren't rendering

**Comment by jaydenmilne** [comment]
Also are things supposed to be tagged here?

**Comment by MaxRobinsonTheGreat** [comment]
In develop the images are working: https://holodeck.readthedocs.io/en/develop/packages/Dexterity/CleanUp/clean-up.html
It should have tags, I will work on that.

**Comment by MaxRobinsonTheGreat** [comment]
Actually all items of trash are tagged as trash, which is useless to document. Closing issue with no changes.
