### ISSUE TITLE
ROS bindings

### ISSUE THREAD

**Issue by mitchneutron** [BYU-PCCL/holodeck#39]
We are hoping to make ROS bindings. It seems that the best way of doing so is either make our python source code work in Python 2.7, or implement it all in c++, and then create the associated ROS bindings. Forking our repository and porting our code to Python 2.7 is probably the easiest/best option.

**Comment by jaydenmilne** [comment]
ROS appears to refer to http://wiki.ros.org/

I don't think this should be on our roadmap
