### ISSUE TITLE
README, Multi agent example are out of date

### ISSUE THREAD

**Issue by vinhowe** [BYU-PCCL/holodeck#391]
**Describe the bug**
The documentation for the [multi agent example](https://holodeck.readthedocs.io/en/latest/usage/examples/multi-agent.html) and the README are out of date because they both use `holodeck.sensors.Sensors`, which no longer exists. 

**To Reproduce**
Look at these files:
https://github.com/BYU-PCCL/holodeck/blame/master/README.md#L99-L101
https://github.com/BYU-PCCL/holodeck/blob/master/docs/usage/examples/multi-agent.rst

**Comment by vinhowe** [comment]
https://github.com/BYU-PCCL/holodeck/blob/master/example.py#L73-L86

**Comment by jaydenmilne** [comment]
#399
