### ISSUE TITLE
posix_ipc.SignalError When making environment

### ISSUE THREAD

**Issue by jmangelson** [BYU-PCCL/holodeck#406]
When making an environment a posix_ipc.SignalError occures. 

Once running the env = holodeck.make("UrbanCity-MaxDistance") command, the error below is immediately thrown. 

The Viewport loads, but because the creation of the environment fails the env object does not exist. 
```python
>>> import holodeck
>>> import numpy as np
>>> env = holodeck.make("UrbanCity-MaxDistance")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joshua/.local/lib/python3.5/site-packages/holodeck/holodeck.py", line 87, in make
    return HolodeckEnvironment(**param_dict)
  File "/home/joshua/.local/lib/python3.5/site-packages/holodeck/environments.py", line 99, in __init__
    show_viewport=show_viewport)
  File "/home/joshua/.local/lib/python3.5/site-packages/holodeck/environments.py", line 626, in __linux_start_process__
    loading_semaphore.acquire(10)
posix_ipc.SignalError: The wait was interrupted by a signal
```

**Comment by jmangelson** [comment]
This discussion seems relevent:

https://groups.google.com/forum/#!topic/comp.lang.python/raOemE38PaY

**Comment by jaydenmilne** [comment]
What version of Linux are you using?

**Comment by jmangelson** [comment]
I'm using Ubuntu 16.04

Joshua Mangelson, Ph.D.
Post-Doctoral Research Fellow
Robotic Perception Lab
Carnegie Mellon University, RI
http://robots.engin.umich.edu/~joshuagm/

**Comment by jaydenmilne** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	margin-bottom:.0001pt;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
span.DefaultFontHxMailStyle
	{mso-style-name:"Default Font HxMail Style";
	font-family:"Arial",sans-serif;
	color:windowtext;
	font-weight:normal;
	font-style:normal;
	text-decoration:none none;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}

**Comment by jmangelson** [comment]
I think you are right that we potentially can just swallow the exception.




Joshua Mangelson, Ph.D.
Post-Doctoral Research Fellow
Robotic Perception Lab
Carnegie Mellon University, RI
http://robots.engin.umich.edu/~joshuagm/

**Comment by jmangelson** [comment]
I'm not sure what is different on my machine. Its been a while since I did
the ubuntu install, so it could be multiple things.


Joshua Mangelson, Ph.D.
Post-Doctoral Research Fellow
Robotic Perception Lab
Carnegie Mellon University, RI
http://robots.engin.umich.edu/~joshuagm/

**Comment by jmangelson** [comment]
So, I tried modifying line 630 in environments.py to ignore the exception:
        except posix_ipc.SignalError:
            pass

It now complains with a semaphore error:

>>> import holodeck
>>> env = holodeck.make("UrbanCity-MaxDistance")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"/home/joshua/.local/lib/python3.5/site-packages/holodeck/holodeck.py",
line 87, in make
    return HolodeckEnvironment(**param_dict)
  File
"/home/joshua/.local/lib/python3.5/site-packages/holodeck/environments.py",
line 106, in __init__
    self._client = HolodeckClient(self._uuid, start_world)
  File
"/home/joshua/.local/lib/python3.5/site-packages/holodeck/holodeckclient.py",
line 35, in __init__
    self.__posix_init__()
  File
"/home/joshua/.local/lib/python3.5/site-packages/holodeck/holodeckclient.py",
line 70, in __posix_init__
    self._semaphore1 = posix_ipc.Semaphore("/HOLODECK_SEMAPHORE_SERVER" +
self._uuid)
posix_ipc.ExistentialError: No semaphore exists with the specified name

Joshua Mangelson, PhD
Post-Doctoral Research Fellow
Robotic Perception Lab
Field Robotics Center, RI
Carnegie Mellon University
http://robots.engin.umich.edu/~joshuagm/

**Comment by jmangelson** [comment]
I tried it on a clean install of 18.04 and it works fine.

**Comment by jaydenmilne** [comment]
Strange. Well I'm glad you got it working, let's hope it doesn't come up again
