### ISSUE TITLE
Entire Test Suite Cannot Be Run on Docker

### ISSUE THREAD

**Issue by jaydenmilne** [BYU-PCCL/holodeck#407]
**Describe the bug**
When you try and run the tests in a Docker container, it will eventually crash because there are too many files open.

**To Reproduce**
Run all of the tests in a Docker container. You can run individual tests and modules but not all of them.

**Comment by vinhowe** [comment]
Related to #356

**Comment by daniekpo** [comment]
Might also be related to #414. I could not reproduce #414 but I think they might be related

**Comment by daniekpo** [comment]
Resolved in #418
