### ISSUE TITLE
CyberPunkCity-Follow Agent ActionSpace

### ISSUE THREAD

**Issue by kolbytn** [BYU-PCCL/holodeck#413]
**Describe the bug**
Action spaces for both agents on this config return a list of `None` for `get_high` and `get_low`

**To Reproduce**
Run `CyberPunkCity-Follow` scenario

**Expected behavior**
`get_high` and `get_low` should return a list of float values associated with those agents

**Version Information:**
 - Ubuntu
 - Holodeck Version 0.3.1

**Comment by daniekpo** [comment]
@kolbytn `UavAgent` doesn't have any restrictions on the second control scheme that's why we return None. I think -inf and inf would probably be better. I could not repro the bug on the second agent in that scenario (`nav0`). I got the correct high and low values.

**Comment by kolbytn** [comment]
Oh I see it now. Not sure why I was getting that for the nav agent. You can close this. `inf` may be better, but I'll leave that up to you.

**Comment by daniekpo** [comment]
Fixed in #417
