### ISSUE TITLE
Command.add_number_parameters silently fails if given numpy array

### ISSUE THREAD

**Issue by sethmnielsen** [BYU-PCCL/holodeck#427]
**Describe the bug**
The function `Command.add_number_parameters` doesn't format the `_parameters` list correctly if a numpy array is passed in as the arg `number`. This results in the command silently failing (it is only printed in the Engine log, not in the client output). This is true at least for the `RotateSensorCommand`; I haven't tested this with the other commands. 

**To Reproduce**
```python
    import holodeck
    import cv2

    env = holodeck.make('UrbanCity-MaxDistance')
    env.reset()

    cmd0 = [0, 0, 0, 100]
    env.act('uav0', cmd0)

    uav = env.agents['uav0']
    ang = np.array([0,-45, 0])    # <-- change this to just a list of [0, -45, 0], and it works
    uav.sensors['RGBCamera'].rotate(ang)
    cv2.namedWindow('Camera Output')

    for _ in range(1000):
        state = env.tick()
        pixels = state['RGBCamera']
        cv2.imshow('Camera Output', pixels[:, :, :3])
        cv2.waitKey(1)

    cv2.destroyAllWindows()
```
The camera doesn't rotate with this code, because `ang` is a numpy array rather than a list. Changing it to a list fixes it.

**Expected behavior**
Either the camera rotates to the given command, or a warning/error is displayed in the client output.

**Logs**

[HolodeckLog.txt](https://github.com/BYU-PCCL/holodeck/files/4833948/HolodeckLog.txt)

**Version Information:**
 - Ubuntu 18.04
 - Holodeck Version 0.3.1

**Comment by daniekpo** [comment]
@sethmnielsen thanks for pointing this issue out. I just looked at the method signature and it looks like it's expecting a `list` object. We might need to update `holodeck` code to add type hinting. We may just have to include error checking code to check that we're getting a `list`. I wonder if it would provide a better user experience if we accepted a NumPy array and converted it to a `list` in the function.
